// src/app/export.rs
//
// Reverse of `migrate`/import: emit the managed package set as NATIVE manifests
// (Brewfile, requirements.txt, package.json, Aptfile). This is the "no lock-in" escape
// hatch — you can always leave LiNix, or hand a native file to a tool that speaks it.
//
// The per-format renderers are pure (state in, text out) so they are unit-tested without
// touching the filesystem or any backend.

use crate::app::App;
use crate::core::{Error, Result};
use std::path::Path;

/// A managed package reduced to what the exporters need.
pub type Pkg = (String, String, Option<String>);

/// Snapshot the managed set as `(backend, name, version)`, preferring the live installed
/// version and falling back to the recorded one.
pub async fn managed_pkgs(app: &App) -> Vec<Pkg> {
    let recorded: Vec<Pkg> = {
        let state = app.state.lock().await;
        state
            .packages
            .iter()
            .map(|p| (p.backend.clone(), p.name.clone(), p.version.clone()))
            .collect()
    };
    let mut out = Vec::with_capacity(recorded.len());
    for (backend, name, rec) in recorded {
        let version = match app
            .registry
            .get(&backend)
            .and_then(|b| b.as_queryable().cloned())
        {
            Some(q) => match q.info(&name).await {
                Ok(Some(p)) => p.version.or(rec),
                _ => rec,
            },
            None => rec,
        };
        out.push((backend, name, version));
    }
    out
}

/// The formats `export` can emit, plus which output filename each conventionally uses.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Format {
    Brew,
    Pip,
    Npm,
    Apt,
}

impl Format {
    pub fn parse(s: &str) -> Option<Self> {
        Some(match s.to_ascii_lowercase().as_str() {
            "brew" | "brewfile" => Format::Brew,
            "pip" | "requirements" | "pipx" => Format::Pip,
            "npm" | "node" | "package.json" => Format::Npm,
            "apt" | "aptfile" | "deb" => Format::Apt,
            _ => return None,
        })
    }

    pub fn filename(self) -> &'static str {
        match self {
            Format::Brew => "Brewfile",
            Format::Pip => "requirements.txt",
            Format::Npm => "package.json",
            Format::Apt => "Aptfile",
        }
    }

    pub fn all() -> [Format; 4] {
        [Format::Brew, Format::Pip, Format::Npm, Format::Apt]
    }

    /// True if a backend's packages belong in this format's output.
    fn accepts(self, backend: &str) -> bool {
        match self {
            Format::Brew => backend == "brew",
            Format::Pip => backend == "pip" || backend == "pipx",
            Format::Npm => matches!(backend, "npm" | "pnpm" | "yarn" | "bun"),
            Format::Apt => backend == "apt",
        }
    }

    /// Render this format from the managed set. Returns `None` when no package applies (so the
    /// caller can skip writing an empty file and say so honestly).
    pub fn render(self, pkgs: &[Pkg]) -> Option<String> {
        let mut rows: Vec<&Pkg> = pkgs.iter().filter(|(b, _, _)| self.accepts(b)).collect();
        if rows.is_empty() {
            return None;
        }
        rows.sort_by(|a, b| a.1.cmp(&b.1));
        Some(match self {
            Format::Brew => {
                let mut s = String::from("# Generated by `linix export` — Homebrew Bundle\n");
                for (_, name, _) in &rows {
                    s.push_str(&format!("brew \"{}\"\n", name));
                }
                s
            }
            Format::Pip => {
                let mut s = String::from("# Generated by `linix export`\n");
                for (_, name, ver) in &rows {
                    match ver {
                        Some(v) if !v.is_empty() && v != "unknown" => {
                            s.push_str(&format!("{}=={}\n", name, v))
                        }
                        _ => s.push_str(&format!("{}\n", name)),
                    }
                }
                s
            }
            Format::Npm => {
                // A minimal but valid package.json with a dependencies map.
                let deps: serde_json::Map<String, serde_json::Value> = rows
                    .iter()
                    .map(|(_, name, ver)| {
                        let spec = match ver {
                            Some(v) if !v.is_empty() && v != "unknown" => format!("^{}", v),
                            _ => "*".to_string(),
                        };
                        (name.clone(), serde_json::Value::String(spec))
                    })
                    .collect();
                let doc = serde_json::json!({
                    "name": "linix-export",
                    "private": true,
                    "dependencies": deps,
                });
                serde_json::to_string_pretty(&doc).unwrap_or_default() + "\n"
            }
            Format::Apt => {
                let mut s = String::from("# Generated by `linix export`\n");
                for (_, name, _) in &rows {
                    s.push_str(&format!("{}\n", name));
                }
                s
            }
        })
    }
}

/// Emit one or all formats. When `to_stdout`, a single format is printed; otherwise files are
/// written into `out_dir`. Returns the list of (filename, wrote?) for reporting.
pub async fn export(
    app: &App,
    format: Option<Format>,
    out_dir: &Path,
    to_stdout: bool,
) -> Result<Vec<(String, bool)>> {
    let pkgs = managed_pkgs(app).await;
    let formats: Vec<Format> = match format {
        Some(f) => vec![f],
        None => Format::all().to_vec(),
    };

    let mut results = Vec::new();
    if to_stdout {
        // Only meaningful for a single format; print it (or a note if empty).
        let f = formats[0];
        match f.render(&pkgs) {
            Some(text) => print!("{}", text),
            None => eprintln!("# no packages map to {}", f.filename()),
        }
        return Ok(results);
    }

    tokio::fs::create_dir_all(out_dir)
        .await
        .map_err(Error::from)?;
    for f in formats {
        match f.render(&pkgs) {
            Some(text) => {
                let path = out_dir.join(f.filename());
                tokio::fs::write(&path, text).await.map_err(Error::from)?;
                results.push((f.filename().to_string(), true));
            }
            None => results.push((f.filename().to_string(), false)),
        }
    }
    Ok(results)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn p(backend: &str, name: &str, ver: Option<&str>) -> Pkg {
        (backend.into(), name.into(), ver.map(|s| s.into()))
    }

    #[test]
    fn format_parse_accepts_aliases() {
        assert_eq!(Format::parse("brewfile"), Some(Format::Brew));
        assert_eq!(Format::parse("requirements"), Some(Format::Pip));
        assert_eq!(Format::parse("package.json"), Some(Format::Npm));
        assert_eq!(Format::parse("deb"), Some(Format::Apt));
        assert_eq!(Format::parse("nonsense"), None);
    }

    #[test]
    fn brewfile_lists_only_brew_packages() {
        let pkgs = vec![p("brew", "ripgrep", Some("14.1")), p("apt", "curl", None)];
        let out = Format::Brew.render(&pkgs).unwrap();
        assert!(out.contains("brew \"ripgrep\"\n"));
        assert!(!out.contains("curl"));
    }

    #[test]
    fn requirements_pins_versions_and_falls_back() {
        let pkgs = vec![
            p("pip", "requests", Some("2.31.0")),
            p("pipx", "black", None),
            p("npm", "left-pad", Some("1.3.0")),
        ];
        let out = Format::Pip.render(&pkgs).unwrap();
        assert!(out.contains("requests==2.31.0\n"));
        assert!(out.contains("black\n"));
        assert!(!out.contains("left-pad"));
    }

    #[test]
    fn package_json_is_valid_and_scoped_to_node() {
        let pkgs = vec![
            p("yarn", "react", Some("18.2.0")),
            p("pnpm", "vite", None),
            p("apt", "curl", None),
        ];
        let out = Format::Npm.render(&pkgs).unwrap();
        let doc: serde_json::Value = serde_json::from_str(&out).unwrap();
        assert_eq!(doc["dependencies"]["react"], "^18.2.0");
        assert_eq!(doc["dependencies"]["vite"], "*");
        assert!(doc["dependencies"].get("curl").is_none());
    }

    #[test]
    fn empty_when_no_package_applies() {
        let pkgs = vec![p("cargo", "ripgrep", Some("14.1"))];
        assert!(Format::Brew.render(&pkgs).is_none());
        assert!(Format::Apt.render(&pkgs).is_none());
    }
}
