// src/app/export.rs
//
// Reverse of `migrate`/import: emit the managed package set as NATIVE manifests
// (Brewfile, requirements.txt, package.json, Aptfile). This is the "no lock-in" escape
// hatch — you can always leave LiNix, or hand a native file to a tool that speaks it.
//
// The per-format renderers are pure (state in, text out) so they are unit-tested without
// touching the filesystem or any backend.

use crate::app::App;
use crate::core::{Error, Result};
use std::path::{Path, PathBuf};

/// A managed package reduced to what the exporters need.
pub type Pkg = (String, String, Option<String>);

/// Snapshot the managed set as `(backend, name, version)`, preferring the live installed
/// version and falling back to the recorded one.
pub async fn managed_pkgs(app: &App) -> Vec<Pkg> {
    let recorded: Vec<Pkg> = {
        let state = app.state.lock().await;
        state
            .packages
            .iter()
            .map(|p| (p.backend.clone(), p.name.clone(), p.version.clone()))
            .collect()
    };
    let mut out = Vec::with_capacity(recorded.len());
    for (backend, name, rec) in recorded {
        let version = match app
            .registry
            .get(&backend)
            .and_then(|b| b.as_queryable().cloned())
        {
            Some(q) => match q.info(&name).await {
                Ok(Some(p)) => p.version.or(rec),
                _ => rec,
            },
            None => rec,
        };
        out.push((backend, name, version));
    }
    out
}

/// The formats `export` can emit, plus which output filename each conventionally uses.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Format {
    Brew,
    Pip,
    Npm,
    Apt,
}

impl Format {
    pub fn parse(s: &str) -> Option<Self> {
        Some(match s.to_ascii_lowercase().as_str() {
            "brew" | "brewfile" => Format::Brew,
            "pip" | "requirements" | "pipx" => Format::Pip,
            "npm" | "node" | "package.json" => Format::Npm,
            "apt" | "aptfile" | "deb" => Format::Apt,
            _ => return None,
        })
    }

    pub fn filename(self) -> &'static str {
        match self {
            Format::Brew => "Brewfile",
            Format::Pip => "requirements.txt",
            Format::Npm => "package.json",
            Format::Apt => "Aptfile",
        }
    }

    pub fn all() -> [Format; 4] {
        [Format::Brew, Format::Pip, Format::Npm, Format::Apt]
    }

    /// True if a backend's packages belong in this format's output.
    fn accepts(self, backend: &str) -> bool {
        match self {
            Format::Brew => backend == "brew",
            Format::Pip => backend == "pip" || backend == "pipx",
            Format::Npm => matches!(backend, "npm" | "pnpm" | "yarn" | "bun"),
            Format::Apt => backend == "apt",
        }
    }

    /// Render this format from the managed set. Returns `None` when no package applies (so the
    /// caller can skip writing an empty file and say so honestly).
    pub fn render(self, pkgs: &[Pkg]) -> Option<String> {
        let mut rows: Vec<&Pkg> = pkgs.iter().filter(|(b, _, _)| self.accepts(b)).collect();
        if rows.is_empty() {
            return None;
        }
        rows.sort_by(|a, b| a.1.cmp(&b.1));
        Some(match self {
            Format::Brew => {
                let mut s = String::from("# Generated by `linix export` — Homebrew Bundle\n");
                for (_, name, _) in &rows {
                    s.push_str(&format!("brew \"{}\"\n", name));
                }
                s
            }
            Format::Pip => {
                let mut s = String::from("# Generated by `linix export`\n");
                for (_, name, ver) in &rows {
                    match ver {
                        Some(v) if !v.is_empty() && v != "unknown" => {
                            s.push_str(&format!("{}=={}\n", name, v))
                        }
                        _ => s.push_str(&format!("{}\n", name)),
                    }
                }
                s
            }
            Format::Npm => {
                // A minimal but valid package.json with a dependencies map.
                let deps: serde_json::Map<String, serde_json::Value> = rows
                    .iter()
                    .map(|(_, name, ver)| {
                        let spec = match ver {
                            Some(v) if !v.is_empty() && v != "unknown" => format!("^{}", v),
                            _ => "*".to_string(),
                        };
                        (name.clone(), serde_json::Value::String(spec))
                    })
                    .collect();
                let doc = serde_json::json!({
                    "name": "linix-export",
                    "private": true,
                    "dependencies": deps,
                });
                serde_json::to_string_pretty(&doc).unwrap_or_default() + "\n"
            }
            Format::Apt => {
                let mut s = String::from("# Generated by `linix export`\n");
                for (_, name, _) in &rows {
                    s.push_str(&format!("{}\n", name));
                }
                s
            }
        })
    }
}

/// What `export` did, or would do, with one format's file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Outcome {
    /// No package maps to this format, so no file.
    NoPackages,
    Wrote(PathBuf),
    /// The natural filename was taken by a file LiNix did not write, so the export landed
    /// beside it under `renamed`.
    WroteBeside { taken: PathBuf, renamed: PathBuf },
    /// `--dry-run`: this is where the bytes would have gone.
    WouldWrite(PathBuf),
}

/// The export's filename with `.linix` inserted before the extension, used when the real
/// filename is already taken: `package.json` -> `package.linix.json`, `Brewfile` ->
/// `Brewfile.linix`.
fn beside(name: &str) -> String {
    match name.split_once('.') {
        Some((stem, ext)) => format!("{}.linix.{}", stem, ext),
        None => format!("{}.linix", name),
    }
}

/// The first free name in the `beside` family, so a second export never clobbers the first
/// export's fallback either.
async fn free_path(out_dir: &Path, name: &str) -> PathBuf {
    let first = out_dir.join(beside(name));
    if !tokio::fs::try_exists(&first).await.unwrap_or(false) {
        return first;
    }
    for n in 2..1000 {
        let p = out_dir.join(format!("{}.{}", beside(name), n));
        if !tokio::fs::try_exists(&p).await.unwrap_or(false) {
            return p;
        }
    }
    first
}

/// Emit one or all formats. When `to_stdout`, a single format is printed; otherwise files are
/// written into `out_dir`.
///
/// `export` runs in directories full of real files it did not create — the default `out_dir`
/// is `.`, and `package.json`/`Brewfile` are exactly the names a real project already uses.
/// So an existing file is never replaced unless `force` says to: the export goes to a
/// non-colliding name instead, and the caller reports where.
pub async fn export(
    app: &App,
    format: Option<Format>,
    out_dir: &Path,
    to_stdout: bool,
    force: bool,
    dry_run: bool,
) -> Result<Vec<(String, Outcome)>> {
    let pkgs = managed_pkgs(app).await;
    let formats: Vec<Format> = match format {
        Some(f) => vec![f],
        None => Format::all().to_vec(),
    };

    let mut results = Vec::new();
    if to_stdout {
        // Only meaningful for a single format; print it (or a note if empty).
        let f = formats[0];
        match f.render(&pkgs) {
            Some(text) => print!("{}", text),
            None => eprintln!("# no packages map to {}", f.filename()),
        }
        return Ok(results);
    }

    if !dry_run {
        tokio::fs::create_dir_all(out_dir)
            .await
            .map_err(Error::from)?;
    }
    for f in formats {
        let name = f.filename().to_string();
        let text = match f.render(&pkgs) {
            Some(t) => t,
            None => {
                results.push((name, Outcome::NoPackages));
                continue;
            }
        };
        let natural = out_dir.join(&name);
        let taken = tokio::fs::try_exists(&natural).await.unwrap_or(false);

        let (target, outcome) = if taken && !force {
            let alt = free_path(out_dir, &name).await;
            let o = if dry_run {
                Outcome::WouldWrite(alt.clone())
            } else {
                Outcome::WroteBeside {
                    taken: natural.clone(),
                    renamed: alt.clone(),
                }
            };
            (alt, o)
        } else if dry_run {
            (natural.clone(), Outcome::WouldWrite(natural.clone()))
        } else {
            (natural.clone(), Outcome::Wrote(natural.clone()))
        };

        if !dry_run {
            tokio::fs::write(&target, text).await.map_err(Error::from)?;
        }
        results.push((name, outcome));
    }
    Ok(results)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn p(backend: &str, name: &str, ver: Option<&str>) -> Pkg {
        (backend.into(), name.into(), ver.map(|s| s.into()))
    }

    #[test]
    fn format_parse_accepts_aliases() {
        assert_eq!(Format::parse("brewfile"), Some(Format::Brew));
        assert_eq!(Format::parse("requirements"), Some(Format::Pip));
        assert_eq!(Format::parse("package.json"), Some(Format::Npm));
        assert_eq!(Format::parse("deb"), Some(Format::Apt));
        assert_eq!(Format::parse("nonsense"), None);
    }

    #[test]
    fn brewfile_lists_only_brew_packages() {
        let pkgs = vec![p("brew", "ripgrep", Some("14.1")), p("apt", "curl", None)];
        let out = Format::Brew.render(&pkgs).unwrap();
        assert!(out.contains("brew \"ripgrep\"\n"));
        assert!(!out.contains("curl"));
    }

    #[test]
    fn requirements_pins_versions_and_falls_back() {
        let pkgs = vec![
            p("pip", "requests", Some("2.31.0")),
            p("pipx", "black", None),
            p("npm", "left-pad", Some("1.3.0")),
        ];
        let out = Format::Pip.render(&pkgs).unwrap();
        assert!(out.contains("requests==2.31.0\n"));
        assert!(out.contains("black\n"));
        assert!(!out.contains("left-pad"));
    }

    #[test]
    fn package_json_is_valid_and_scoped_to_node() {
        let pkgs = vec![
            p("yarn", "react", Some("18.2.0")),
            p("pnpm", "vite", None),
            p("apt", "curl", None),
        ];
        let out = Format::Npm.render(&pkgs).unwrap();
        let doc: serde_json::Value = serde_json::from_str(&out).unwrap();
        assert_eq!(doc["dependencies"]["react"], "^18.2.0");
        assert_eq!(doc["dependencies"]["vite"], "*");
        assert!(doc["dependencies"].get("curl").is_none());
    }

    #[test]
    fn empty_when_no_package_applies() {
        let pkgs = vec![p("cargo", "ripgrep", Some("14.1"))];
        assert!(Format::Brew.render(&pkgs).is_none());
        assert!(Format::Apt.render(&pkgs).is_none());
    }

    #[test]
    fn beside_keeps_the_extension_readable() {
        assert_eq!(beside("package.json"), "package.linix.json");
        assert_eq!(beside("requirements.txt"), "requirements.linix.txt");
        assert_eq!(beside("Brewfile"), "Brewfile.linix");
        assert_eq!(beside("Aptfile"), "Aptfile.linix");
    }

    #[tokio::test]
    async fn free_path_steps_past_a_fallback_that_is_also_taken() {
        let dir = tempfile::tempdir().unwrap();
        let d = dir.path();

        // Nothing taken: the plain `.linix` name.
        assert_eq!(free_path(d, "package.json").await, d.join("package.linix.json"));

        // The fallback itself exists, so a second export must not clobber the first one's.
        tokio::fs::write(d.join("package.linix.json"), "first").await.unwrap();
        assert_eq!(
            free_path(d, "package.json").await,
            d.join("package.linix.json.2")
        );
    }
}
