pub mod bisect;
pub mod bundle;
pub mod conflicts;
pub mod context;
pub mod diagnostics;
pub mod export;
pub mod fleet;
pub mod generation;
pub mod hooks;
pub mod insight;
pub mod metrics;
pub mod migrate;
pub mod module_registry;
pub mod pm_hooks;
pub mod policy;
pub mod profile;
pub mod profile_expr;
pub mod run;
pub mod sandbox;
pub mod search;
pub mod services;
pub mod shim_manager;
pub mod sync;
pub mod teleport;
pub mod ui;
pub mod undo;

pub mod scheduler;
pub mod shell;

pub use self::context::App;
pub use self::hooks::LuaHooks;
pub use self::metrics::MetricsCollector;
pub use self::search::UniversalSearch;
pub use self::sync::SyncEngine;
pub use self::run::Runner;
pub use self::migrate::Migrator;
pub use self::teleport::Teleporter;
pub use self::shim_manager::ShimManager;
pub use self::undo::UndoManager;
pub use self::profile::ProfileManager;
pub use self::shell::GhostShell;

pub const APP_NAME: &str = "linix";
pub const DEFAULT_CONFIG_NAME: &str = "config.toml";
