pub mod registry;
#[cfg(target_os = "linux")] pub mod apk;
#[cfg(target_os = "linux")] pub mod apt;
#[cfg(target_os = "linux")] pub mod dnf;
#[cfg(target_os = "linux")] pub mod pacman;
#[cfg(target_os = "linux")] pub mod zypper;
pub mod brew;
pub mod flatpak;
pub mod snap;
pub mod bun;
pub mod cargo;
pub mod composer;
pub mod gem;
pub mod go;
pub mod npm;
pub mod pip;
pub mod pipx;
pub mod poetry;
pub mod yarn;
pub mod github;
pub mod uv;
pub mod pnpm;
pub mod vscode;
pub mod mise;
pub mod web;
pub mod link;
pub mod emacs;
#[cfg(target_os = "windows")] pub mod windows;
pub use registry::{create_default_registry, BackendRegistry};