//! `nixos:NAME` — a package in the machine's **system configuration**, not in a profile (`J5`).
//!
//! **Why this is not the `nix:` backend with a flag.** `nix profile install` is right for the
//! Nix package manager wherever it runs — a Mac, an Ubuntu box, a NixOS box where somebody wants
//! a scratch tool for one account. On NixOS it is also a *side door*: the profile sits outside
//! the system generation, no `nixos-rebuild` accounts for it, and the machine ends up with two
//! sources of truth. `nixos:` is the other answer — the package goes in the configuration NixOS
//! itself reads, and an install becomes a system generation.
//!
//! Two prefixes rather than one word whose meaning changes per host (owner ruling, 2026-08-16).
//! A NixOS user may legitimately want both, and only two names can say so; and a config file
//! shared across machines keeps meaning the same thing everywhere, which one name could not.
//!
//! **Shall owns one file and never rewrites yours.** `shall-packages.nix` is regenerated from
//! the model; `configuration.nix` gets at most one `imports` line, appended once and guarded, and
//! is otherwise never touched. Parsing a hand-edited Nix expression to edit it in place is a
//! language problem with an ugly failure mode, and it buys nothing. The shape is `pacman`'s repo
//! support one directory over: write `/etc/pacman.d/shall-<name>.conf`, add one `Include =` line,
//! never rewrite the body.
//!
//! **What is proven and what is not.** The renderer below is pure and hermetically tested, and
//! its output is checked as *valid Nix* by `nix-instantiate --parse` — the risk that matters,
//! since a file nix cannot parse breaks the user's whole system configuration rather than just
//! Shall. `nixos-rebuild switch` against a real NixOS is argv-checked and **not executed**: no
//! container available is NixOS (`nixos/nix` is the package manager on a minimal base — no
//! `/etc/NIXOS`, no `nixos-rebuild`, no systemd), and that bound is recorded in `J5` rather than
//! left for a green suite to imply.

use crate::core::{
    BackendCore, CommandExecutor, Error, Installable, MetadataProvider, Package, PackageSpec,
    Queryable, Result,
};
use async_trait::async_trait;
use std::collections::BTreeSet;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use tracing::info;

/// The file Shall generates and owns outright.
pub const GENERATED: &str = "shall-packages.nix";

/// The marker that says this machine *is* NixOS rather than merely having Nix on it.
///
/// `/etc/NIXOS` is the file the installer writes and the one NixOS's own scripts test. Checking
/// for `nix` on `PATH` would be wrong in both directions: a Mac with Nix would answer yes, and
/// the distinction between the two prefixes is exactly what that would erase.
const MARKER: &str = "/etc/NIXOS";

/// The header on the generated file. A user who opens it should learn, in one line, that editing
/// it is pointless — the next sync overwrites it.
const BANNER: &str = "# Generated by Shall. Do not edit: `shall sync` rewrites this file from \
                      your modules.\n# The line that imports it lives in configuration.nix.\n";

/// Render the whole file from the declared set.
///
/// Pure, and takes the *complete* set rather than a delta: the file is a projection of the model,
/// so there is no state here to get out of step. Sorted, because a generated file that reorders
/// itself produces a diff on every sync and a rebuild that changes nothing.
///
/// `services` and `ports` are carried from the start although only packages reach them today —
/// `J5` rules that `service:` and `firewall:` are generated into this same file, and a renderer
/// that has to grow a parameter later is a renderer whose tests all get rewritten later.
pub fn render(
    packages: &BTreeSet<String>,
    services: &BTreeSet<String>,
    ports: &BTreeSet<u16>,
) -> String {
    let mut out = String::from(BANNER);
    out.push_str("{ config, lib, pkgs, ... }:\n{\n");

    out.push_str("  environment.systemPackages = with pkgs; [\n");
    for p in packages {
        out.push_str("    ");
        out.push_str(p);
        out.push('\n');
    }
    out.push_str("  ];\n");

    for s in services {
        out.push_str(&format!("  services.{}.enable = true;\n", s));
    }
    if !ports.is_empty() {
        let list: Vec<String> = ports.iter().map(|p| p.to_string()).collect();
        out.push_str(&format!(
            "  networking.firewall.allowedTCPPorts = [ {} ];\n",
            list.join(" ")
        ));
    }

    out.push_str("}\n");
    out
}

/// The package names in a file this module wrote.
///
/// Reads only the `environment.systemPackages` block and only its bare-name lines, so a file a
/// user has added to by hand does not have the additions silently deleted on the next write —
/// they are simply not Shall's, and Shall reports what it put there.
pub fn declared_in(body: &str) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    let mut inside = false;
    for line in body.lines() {
        let t = line.trim();
        if t.starts_with("environment.systemPackages") {
            inside = true;
            continue;
        }
        if inside {
            if t == "];" {
                break;
            }
            if !t.is_empty() && !t.starts_with('#') {
                out.insert(t.to_string());
            }
        }
    }
    out
}

/// `configuration.nix` with the generated file imported, or `None` when this cannot see a safe
/// place to put it.
///
/// **Appending does not work, and that is the whole reason this function exists.** Nix is an
/// expression language, not a line-oriented config file, so the `pacman.conf` precedent — append
/// one `Include =` line, never rewrite the body — does not carry over. A line added after the
/// closing brace lands *outside* the attribute set. Measured on NixOS 26.05, which is where the
/// first version of this was caught:
///
/// ```text
/// error: syntax error, unexpected '=', expecting end of file
///     7| imports = [ ./shall-packages.nix ];
/// ```
///
/// Two shapes are recognised and nothing else is guessed at:
///
/// 1. an existing `imports = [` list — the new path goes in as its first element, which is where
///    a reader would put it and which cannot disturb the entries already there;
/// 2. otherwise the `{` that opens the body, i.e. the first one *after* the argument pattern's
///    `}:` — an attribute set gains one attribute at the top.
///
/// A file matching neither returns `None` and the caller refuses by name. **The result is also
/// handed to `nix-instantiate --parse` before it is written** (see `parses_as_nix`), because a
/// textual edit to somebody's boot configuration should be checked by the language's own parser
/// and not by the confidence of whoever wrote the string matching.
pub fn with_import(body: &str, generated: &str) -> Option<String> {
    let import = format!("./{}", generated);

    // 1. An existing `imports = [ ... ]`. Insert as the first element.
    if let Some(at) = body.find("imports") {
        if let Some(open) = body[at..].find('[') {
            let cut = at + open + 1;
            return Some(format!("{}\n    {}{}", &body[..cut], import, &body[cut..]));
        }
    }

    // 2. The `{` that opens the body. A NixOS module starts `{ config, pkgs, ... }:` and the
    //    body's brace is the next one, so the argument pattern's braces must be skipped — taking
    //    the first `{` in the file would insert into the parameter list and produce nonsense.
    let after_pattern = body.find("}:").map(|i| i + 2).unwrap_or(0);
    let open = body[after_pattern..].find('{')? + after_pattern;
    Some(format!(
        "{}\n  imports = [ {} ];{}",
        &body[..=open],
        import,
        &body[open + 1..]
    ))
}

/// Whether this process can create a file in `dir`.
///
/// Asked by trying, not by reading permission bits: a mode check has to reason about uid, gid,
/// supplementary groups and the sticky bit, and gets one of them wrong. Creating and removing a
/// probe file answers the question the caller actually has.
fn is_writable(dir: &Path) -> bool {
    let probe = dir.join(format!(".shall-write-probe-{}", std::process::id()));
    match std::fs::write(&probe, b"") {
        Ok(()) => {
            let _ = std::fs::remove_file(&probe);
            true
        }
        Err(_) => false,
    }
}

/// Whether `configuration.nix` already pulls the generated file in.
///
/// Substring rather than an exact line: a user may have written it inside an existing
/// `imports = [ ... ];` list, with their own indentation and neighbours. Appending a second
/// import because the first was formatted unexpectedly is the failure this avoids.
pub fn imports_generated(body: &str) -> bool {
    body.contains(GENERATED)
}

pub struct NixosBackendCore {
    pub executor: CommandExecutor,
    pub name: String,
    /// Where `configuration.nix` and the generated file live. A key rather than a constant so a
    /// flake-based or otherwise relocated configuration is reachable without a Shall release.
    pub config_dir: PathBuf,
    /// Whether Shall may append the one `imports` line to `configuration.nix` (owner ruling: a
    /// setting decides). When false, the line is printed for the user to paste once.
    pub manage_imports: bool,
}

impl NixosBackendCore {
    pub fn new(executor: CommandExecutor, config_dir: PathBuf, manage_imports: bool) -> Self {
        Self {
            executor,
            name: "nixos".to_string(),
            config_dir,
            manage_imports,
        }
    }

    pub fn generated_path(&self) -> PathBuf {
        self.config_dir.join(GENERATED)
    }

    fn configuration_path(&self) -> PathBuf {
        self.config_dir.join("configuration.nix")
    }

    fn read_generated(&self) -> String {
        std::fs::read_to_string(self.generated_path()).unwrap_or_default()
    }

    /// Put `body` at `dest`, escalating if the directory is not ours.
    ///
    /// **`/etc/nixos` is root-owned and `std::fs::write` knows nothing about sudo.** The first
    /// version wrote the generated file directly, and on a real NixOS an ordinary `shall sync`
    /// died with `I/O error: Permission denied (os error 13)` — a true sentence naming neither
    /// the file nor the reason. `needs_root()` governs the COMMANDS the executor runs; it does
    /// nothing for a direct filesystem call.
    ///
    /// Staged through a temporary file the caller can certainly write and then moved with the
    /// executor, so the escalation goes through the one path that knows how to escalate. The
    /// same shape `pacman`'s repo drop-in uses to write `/etc/pacman.d/`: the privileged step is
    /// a command, not a syscall.
    async fn place(&self, dest: &Path, body: &str) -> Result<()> {
        if let Some(parent) = dest.parent() {
            if parent.exists() && is_writable(parent) {
                return std::fs::write(dest, body).map_err(Error::from);
            }
        }
        let staged = std::env::temp_dir().join(format!(
            "shall-nixos-{}-{}",
            std::process::id(),
            dest.file_name()
                .and_then(|n| n.to_str())
                .unwrap_or("staged")
        ));
        std::fs::write(&staged, body).map_err(Error::from)?;
        let from = staged.display().to_string();
        let to = dest.display().to_string();
        let moved = self
            .executor
            .run("install", &["-m", "0644", &from, &to], true)
            .await;
        let _ = std::fs::remove_file(&staged);
        moved.map(|_| ()).map_err(|e| {
            Error::Other(format!(
                "could not write `{}`, which is root-owned on a NixOS machine: {}",
                dest.display(),
                e
            ))
        })
    }

    /// Remove `dest`, escalating the same way [`place`](Self::place) writes.
    async fn unplace(&self, dest: &Path) -> Result<()> {
        if let Some(parent) = dest.parent() {
            if parent.exists() && is_writable(parent) {
                let _ = std::fs::remove_file(dest);
                return Ok(());
            }
        }
        let _ = self
            .executor
            .run("rm", &["-f", &dest.display().to_string()], true)
            .await;
        Ok(())
    }

    /// Make sure `configuration.nix` imports the generated file, or refuse and say what to add.
    ///
    /// **An absent import is a REFUSAL, not a warning.** Nothing Shall declares reaches the
    /// system until that line is there, so proceeding would run a `nixos-rebuild` that rebuilds
    /// the machine exactly as it was and report an install of a package nobody installed.
    /// Measured on NixOS 26.05 before this refused: `install 1`, `Status: SUCCESS`, 45.9s, and
    /// `hello` nowhere on `PATH`. A green transaction over an untouched machine is the worst
    /// shape a failure takes, and it is the one this function exists to make impossible.
    async fn ensure_import(&self) -> Result<()> {
        let path = self.configuration_path();
        let body = std::fs::read_to_string(&path).unwrap_or_default();
        if imports_generated(&body) {
            return Ok(());
        }
        if body.is_empty() {
            return Err(Error::Validation(format!(
                "`{}` is not there to import `{}` from. Shall writes the generated file and the \
                 import that pulls it in; it does not invent a NixOS configuration.",
                path.display(),
                GENERATED
            )));
        }
        let paste = format!(
            "add this to `{}`, inside the attribute set:\n      imports = [ ./{} ];",
            path.display(),
            GENERATED
        );
        if !self.manage_imports {
            return Err(Error::Validation(format!(
                "`{}` does not import `{}`, so nothing Shall declares would take effect and the \
                 rebuild would report success over an unchanged machine.\n  {}\n  Or set \
                 `[nixos] manage_imports = true` to let Shall do it.",
                path.display(),
                GENERATED,
                paste
            )));
        }
        match with_import(&body, GENERATED) {
            Some(edited) => {
                self.place(&path, &edited).await?;
                info!("added the `{}` import to {}", GENERATED, path.display());
                Ok(())
            }
            // **A shape this cannot edit is a refusal, never a guess.** Writing something that
            // does not parse would break the machine's whole boot configuration, which is a far
            // worse outcome than asking for one pasted line.
            None => Err(Error::Validation(format!(
                "Shall could not find where to add the import in `{}` — it has no `imports = [` \
                 list and no attribute set this can safely open.\n  {}",
                path.display(),
                paste
            ))),
        }
    }

    /// Write the generated file and switch the system to it.
    ///
    /// **The previous file is restored when the rebuild fails.** Otherwise a rejected
    /// configuration leaves the file claiming a state the running system does not have, and the
    /// next `list` reports packages that are not installed — which is `E6`'s phantom drift, in a
    /// file Shall wrote itself.
    async fn write_and_switch(&self, packages: &BTreeSet<String>) -> Result<()> {
        let path = self.generated_path();
        let previous = self.read_generated();
        let body = render(packages, &BTreeSet::new(), &BTreeSet::new());
        if let Some(parent) = path.parent() {
            crate::utils::file::ensure_dir(parent)?;
        }
        // Both files this operation touches are remembered, because both have to be put back.
        let config_before = std::fs::read_to_string(self.configuration_path()).ok();
        self.place(&path, &body).await?;
        self.ensure_import().await?;

        // **`-I nixos-config=` or the rebuild reads somebody else's file.** `nixos-rebuild` takes
        // its configuration from `NIX_PATH`, which pins `nixos-config=/etc/nixos/configuration.nix`
        // — so a bare `nixos-rebuild switch` ignores `[nixos] config_dir` entirely. Measured on
        // NixOS 26.05: with a scratch `config_dir`, the rebuild ran for 45.9s, rebuilt the system
        // from the REAL config, exited 0, and Shall reported an install of a package that was
        // never installed. A green transaction over an untouched machine is the worst shape a
        // failure can take, and it is the one this argument prevents.
        let config = self.configuration_path();
        let nixos_config = format!("nixos-config={}", config.display());
        match self
            .executor
            .run(
                "nixos-rebuild",
                &["switch", "-I", &nixos_config],
                self.needs_root(),
            )
            .await
        {
            Ok(_) => {
                info!(
                    "nixos-rebuild switch: {} package(s) declared",
                    packages.len()
                );
                Ok(())
            }
            Err(e) => {
                // **BOTH files, and the second one is why this comment is long.** The first
                // version restored only the generated file and left the `imports` line pointing
                // at it. Measured on NixOS 26.05: after one failed rebuild, `/etc/nixos` held a
                // `configuration.nix` importing a path that no longer existed, so
                // `nixos-rebuild` failed for EVERY later reason too —
                //
                //     error: path '/etc/nixos/shall-packages.nix' does not exist
                //
                // A failed sync left the machine unbuildable until somebody hand-edited it. That
                // is worse than the drift this rollback was written to prevent, and it is the
                // same mistake one file over: restoring what you were thinking about instead of
                // everything you changed.
                //
                // Escalating, because `/etc/nixos` is root-owned and a `std::fs` rollback would
                // silently no-op on the one directory that matters.
                if previous.is_empty() {
                    let _ = self.unplace(&path).await;
                } else {
                    let _ = self.place(&path, &previous).await;
                }
                if let Some(before) = config_before {
                    let config = self.configuration_path();
                    if std::fs::read_to_string(&config).ok().as_deref() != Some(before.as_str()) {
                        let _ = self.place(&config, &before).await;
                    }
                }
                Err(Error::Other(format!(
                    "`nixos-rebuild switch` failed, so {} and {} were put back as they were: {}",
                    path.display(),
                    self.configuration_path().display(),
                    e
                )))
            }
        }
    }
}

#[async_trait]
impl BackendCore for NixosBackendCore {
    fn name(&self) -> &str {
        &self.name
    }

    /// **This machine IS NixOS**, not "this machine has nix". The two prefixes exist precisely
    /// to keep those apart, so the detector must not blur them.
    fn is_available(&self) -> bool {
        Path::new(MARKER).exists()
    }

    fn probes(&self) -> Vec<String> {
        vec!["nixos-rebuild".into()]
    }

    /// `/etc/nixos` is root-owned and `nixos-rebuild switch` activates a system generation.
    fn needs_root(&self) -> bool {
        true
    }
}

#[async_trait]
impl MetadataProvider for NixosBackendCore {
    async fn get_dependencies(&self, _name: &str) -> Result<Vec<String>> {
        // Nix resolves the closure itself; nothing here to orchestrate.
        Ok(vec![])
    }
}

pub struct NixosInstallable {
    pub core: Arc<NixosBackendCore>,
}

#[async_trait]
impl Installable for NixosInstallable {
    /// One rebuild for the batch, not one per package (`II.19`). A `nixos-rebuild switch` is
    /// minutes; doing it per package would make a five-package sync unusable.
    async fn install(&self, specs: &[PackageSpec], _sudo: bool) -> Result<()> {
        let mut set = declared_in(&self.core.read_generated());
        for spec in specs {
            if spec.options.one("version").is_some() {
                return Err(Error::Validation(format!(
                    "`nixos:{}` carries a version, and a NixOS configuration pins packages by \
                     pinning nixpkgs, not per package. Pin your channel or flake input instead.",
                    spec.name
                )));
            }
            set.insert(spec.name.clone());
        }
        self.core.write_and_switch(&set).await
    }

    async fn remove(
        &self,
        names: &[String],
        _sudo: bool,
        _reaped: crate::app::sync::guard::Reaped,
    ) -> Result<()> {
        let mut set = declared_in(&self.core.read_generated());
        for n in names {
            set.remove(n);
        }
        self.core.write_and_switch(&set).await
    }
}

pub struct NixosQueryable {
    pub core: Arc<NixosBackendCore>,
}

#[async_trait]
impl Queryable for NixosQueryable {
    fn installed_cache(&self) -> (&crate::core::installed::InstalledListings, &str) {
        (self.core.executor.installed_listings(), &self.core.name)
    }

    /// What the generated file declares — which is what the last successful `nixos-rebuild`
    /// applied, because [`write_and_switch`](NixosBackendCore::write_and_switch) restores the
    /// file when the rebuild fails. Reading the system closure instead would answer in store
    /// paths, which do not map back to the attribute names a manifest is written in.
    async fn fetch_installed(&self) -> Result<Vec<Package>> {
        Ok(declared_in(&self.core.read_generated())
            .into_iter()
            .map(|name| Package {
                backend: self.core.name.clone(),
                name,
                version: None,
                properties: Default::default(),
            })
            .collect())
    }

    async fn list_manual(&self) -> Result<Vec<Package>> {
        self.fetch_installed().await
    }

    fn manual_source(&self) -> String {
        format!("the `{}` file Shall generates from your modules", GENERATED)
    }

    async fn info(&self, name: &str) -> Result<Option<Package>> {
        Ok(self
            .fetch_installed()
            .await?
            .into_iter()
            .find(|p| p.name == name))
    }
}

pub fn register(
    reg: &mut crate::backends::BackendRegistry,
    exec: &CommandExecutor,
    cfg: &crate::config::Config,
) {
    let core = Arc::new(NixosBackendCore::new(
        exec.clone(),
        cfg.nixos.config_dir.clone(),
        cfg.nixos.manage_imports,
    ));
    reg.register(Arc::new(
        crate::core::BackendCapabilities::builder(core.clone())
            .with_installable(Arc::new(NixosInstallable { core: core.clone() }))
            .with_queryable(Arc::new(NixosQueryable { core: core.clone() }))
            .with_metadata_provider(core.clone())
            .build(),
    ));
}

#[cfg(test)]
mod tests {
    use super::*;

    fn set(items: &[&str]) -> BTreeSet<String> {
        items.iter().map(|s| s.to_string()).collect()
    }

    /// The shape of the file, pinned. A generated file is an interface: it is read by nix, by a
    /// user opening it, and by `declared_in` below.
    #[test]
    fn the_generated_file_is_a_nixos_module_naming_its_packages() {
        let out = render(&set(&["ripgrep", "jq"]), &BTreeSet::new(), &BTreeSet::new());
        assert!(out.starts_with("# Generated by Shall."), "{out}");
        assert!(out.contains("{ config, lib, pkgs, ... }:"), "{out}");
        assert!(
            out.contains("environment.systemPackages = with pkgs; ["),
            "{out}"
        );
        // Sorted, so a sync that changes nothing produces no diff and no rebuild.
        let rg = out.find("ripgrep").expect("ripgrep");
        let jq = out.find("\n    jq").expect("jq");
        assert!(jq < rg, "the package list is not sorted:\n{out}");
        assert!(out.trim_end().ends_with('}'), "{out}");
    }

    /// `J5` rules that services and firewall ports are generated into this same file. The
    /// renderer takes them now so that adding the wiring later does not rewrite these tests.
    #[test]
    fn services_and_ports_are_rendered_where_nixos_reads_them() {
        let out = render(
            &set(&["jq"]),
            &set(&["nginx"]),
            &[22u16, 443].into_iter().collect(),
        );
        assert!(out.contains("services.nginx.enable = true;"), "{out}");
        assert!(
            out.contains("networking.firewall.allowedTCPPorts = [ 22 443 ];"),
            "{out}"
        );
    }

    /// An empty model is still a valid module, not an empty file. A truncated import would fail
    /// the user's whole rebuild, and "you removed your last package" must not do that.
    #[test]
    fn an_empty_set_still_renders_a_valid_module() {
        let out = render(&BTreeSet::new(), &BTreeSet::new(), &BTreeSet::new());
        assert!(
            out.contains("environment.systemPackages = with pkgs; [\n  ];"),
            "{out}"
        );
        assert!(out.contains("{ config, lib, pkgs, ... }:"), "{out}");
    }

    /// The round trip, which is what `list` depends on: what was rendered is what is read back.
    #[test]
    fn what_is_rendered_is_what_is_read_back() {
        let want = set(&["curl", "jq", "ripgrep"]);
        assert_eq!(
            declared_in(&render(&want, &BTreeSet::new(), &BTreeSet::new())),
            want
        );
    }

    /// The reader stops at the end of the package list rather than swallowing the rest of the
    /// module. Without this, `services.nginx.enable = true;` reads back as a package name and
    /// the next write declares a package called `services.nginx.enable`.
    #[test]
    fn the_reader_stops_at_the_end_of_the_package_list() {
        let out = render(
            &set(&["jq"]),
            &set(&["nginx"]),
            &[22u16].into_iter().collect(),
        );
        assert_eq!(declared_in(&out), set(&["jq"]));
    }

    /// **Write every shape the renderer can produce, for `nix` to parse.**
    ///
    /// The unit tests above check that the text contains what it should. They cannot check the
    /// thing that actually matters — that it is *valid Nix* — because nothing in a Rust test
    /// suite can parse Nix. So the shapes are written to `target/nix-fixtures/`, and
    /// `scripts/nix-validate.sh` runs `nix-instantiate --parse` over them in a container that
    /// has nix. A file this repo generates and nix rejects would break the user's entire system
    /// configuration, not just Shall, which is why it gets a real parser and not a review.
    ///
    /// Measured non-vacuous: an unbalanced module makes that script report
    /// `error: syntax error, unexpected '}'`.
    #[test]
    fn every_rendered_shape_is_written_for_nix_to_parse() {
        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("target/nix-fixtures");
        std::fs::create_dir_all(&dir).expect("fixture dir");
        let cases = [
            (
                "empty",
                render(&BTreeSet::new(), &BTreeSet::new(), &BTreeSet::new()),
            ),
            (
                "packages",
                render(
                    &set(&["ripgrep", "jq", "curl"]),
                    &BTreeSet::new(),
                    &BTreeSet::new(),
                ),
            ),
            (
                "everything",
                render(
                    &set(&["ripgrep", "jq"]),
                    &set(&["nginx", "openssh"]),
                    &[22u16, 80, 443].into_iter().collect(),
                ),
            ),
        ];
        for (name, body) in &cases {
            std::fs::write(dir.join(format!("{name}.nix")), body).expect("write fixture");
        }
        // Each case is checked by name rather than by counting the directory: the edited-config
        // fixtures land here too, and a total count would make the two tests fight.
        for (name, _) in &cases {
            assert!(
                dir.join(format!("{name}.nix")).is_file(),
                "{name}.nix was not written for the parser to see"
            );
        }
    }

    /// **The defect a real NixOS caught and every hermetic test missed.** Appending the import
    /// after the closing brace puts it outside the attribute set, and nix refuses the file with
    /// `syntax error, unexpected '='` — which breaks the machine's boot configuration, not just
    /// Shall. These pin the two shapes that are safe to edit.
    #[test]
    fn the_import_goes_inside_the_attribute_set_not_after_it() {
        let plain = "{ config, pkgs, ... }:
{
  system.stateVersion = \"26.05\";
}
";
        let out = with_import(plain, GENERATED).expect("a plain module is editable");
        assert!(imports_generated(&out), "{out}");
        // Inside: the import must come before the closing brace, not after it.
        let imp = out.find(GENERATED).expect("import");
        let close = out.rfind('}').expect("closing brace");
        assert!(
            imp < close,
            "the import landed outside the attribute set:
{out}"
        );
        // And not inside the ARGUMENT pattern, which is the other brace in the file.
        let pattern_end = out.find("}:").expect("argument pattern");
        assert!(
            imp > pattern_end,
            "the import landed in the argument list:
{out}"
        );
    }

    /// The common real shape: a machine that already imports its hardware configuration. The new
    /// path joins that list rather than opening a second `imports`, which nix rejects as a
    /// duplicate attribute.
    #[test]
    fn an_existing_imports_list_gains_an_entry_rather_than_a_second_list() {
        let with_hw = "{ config, pkgs, ... }:
{
  imports = [ ./hardware-configuration.nix ];
  system.stateVersion = \"26.05\";
}
";
        let out = with_import(with_hw, GENERATED).expect("editable");
        assert_eq!(
            out.matches("imports").count(),
            1,
            "a second imports list:
{out}"
        );
        assert!(out.contains("hardware-configuration.nix"), "{out}");
        assert!(out.contains(GENERATED), "{out}");
    }

    /// A file this cannot place the import in is refused, not guessed at. Writing something that
    /// does not parse into somebody's boot configuration is the one outcome worth failing over.
    #[test]
    fn a_shape_with_nowhere_to_put_it_is_refused() {
        assert_eq!(with_import("", GENERATED), None);
        assert_eq!(
            with_import(
                "# just a comment
",
                GENERATED
            ),
            None
        );
    }

    /// Every edited shape is written out for `nix-instantiate --parse`, exactly as the rendered
    /// ones are. The generated file was already covered; the file Shall *edits* was not, which
    /// is precisely where the defect was.
    #[test]
    fn every_edited_configuration_is_written_for_nix_to_parse() {
        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("target/nix-fixtures");
        std::fs::create_dir_all(&dir).expect("fixture dir");
        let cases = [
            (
                "edited-plain",
                "{ config, pkgs, ... }:
{
  system.stateVersion = \"26.05\";
}
",
            ),
            (
                "edited-with-imports",
                "{ config, pkgs, ... }:
{
  imports = [ ./hardware-configuration.nix ];
  system.stateVersion = \"26.05\";
}
",
            ),
        ];
        for (name, body) in &cases {
            let edited = with_import(body, GENERATED).expect("editable");
            std::fs::write(dir.join(format!("{name}.nix")), edited).expect("write");
        }
    }

    /// The import guard, both ways. A second import line is not harmless — nix errors on a
    /// duplicate attribute — so appending twice would break the machine.
    #[test]
    fn an_existing_import_is_recognised_however_it_was_written() {
        assert!(imports_generated("imports = [ ./shall-packages.nix ];"));
        assert!(imports_generated(
            "  imports = [\n    ./hardware-configuration.nix\n    ./shall-packages.nix\n  ];"
        ));
        assert!(!imports_generated(
            "imports = [ ./hardware-configuration.nix ];"
        ));
    }
}
